import { readFile, rename, writeFile } from 'node:fs/promises';

import {
  ApiProblem,
  StateConflict,
  type DocumentBackend,
  type DocumentFilter,
  type DocumentKind,
  type DocumentWrite,
  type VersionedDocument,
} from '@mission-control/api';

interface DiskState {
  readonly revision: number;
  readonly rows: readonly VersionedDocument[];
}

const matches = (
  row: VersionedDocument,
  filters: readonly DocumentFilter[],
) => {
  const value = row.document.value;
  return filters.every(
    (filter) =>
      value !== null &&
      typeof value === 'object' &&
      !Array.isArray(value) &&
      value[filter.field] === filter.value,
  );
};

/** Atomic file transport double for offline restart tests, never a hosted adapter. */
export class FileDocumentBackend implements DocumentBackend {
  static readonly #accesses = new Map<string, Promise<unknown>>();
  readonly batches: (readonly DocumentWrite[])[] = [];
  failBeforeKind: DocumentKind | undefined;
  failAfterKind: DocumentKind | undefined;
  beforeBatch:
    ((writes: readonly DocumentWrite[]) => Promise<void>) | undefined;

  constructor(private readonly path: string) {}

  async #access<T>(operation: () => Promise<T>): Promise<T> {
    // Windows cannot replace a file while another operation still holds its read handle.
    // Lock individual file operations, not the application's multi-operation transactions.
    const previous =
      FileDocumentBackend.#accesses.get(this.path) ?? Promise.resolve();
    const result = previous.then(operation, operation);
    FileDocumentBackend.#accesses.set(this.path, result);
    try {
      return await result;
    } finally {
      if (FileDocumentBackend.#accesses.get(this.path) === result)
        FileDocumentBackend.#accesses.delete(this.path);
    }
  }

  async #load(): Promise<DiskState> {
    try {
      // This fixture reads only the JSON generated by its own atomic writer.
      return JSON.parse(await readFile(this.path, 'utf8')) as DiskState;
    } catch (error) {
      if (error instanceof Error && 'code' in error && error.code === 'ENOENT')
        return { revision: 0, rows: [] };
      throw error;
    }
  }

  read(partition: string, id: string) {
    return this.#access(async () =>
      (await this.#load()).rows.find(
        ({ document }) =>
          document.eventSessionId === partition && document.id === id,
      ),
    );
  }

  query(
    kind: DocumentKind,
    partition?: string,
    filters: readonly DocumentFilter[] = [],
  ) {
    return this.#access(async () =>
      (await this.#load()).rows.filter(
        (row) =>
          row.document.kind === kind &&
          (partition === undefined ||
            row.document.eventSessionId === partition) &&
          matches(row, filters),
      ),
    );
  }

  async batch(partition: string, writes: readonly DocumentWrite[]) {
    await this.beforeBatch?.(writes);
    return this.#access(async () => {
      if (writes.some(({ document }) => document.eventSessionId !== partition))
        throw new Error('A transaction crossed event partitions.');
      if (
        writes.some(({ document }) => document.kind === this.failBeforeKind)
      ) {
        this.failBeforeKind = undefined;
        throw this.#failure();
      }
      const current = await this.#load();
      const rows = new Map(
        current.rows.map((row) => [
          JSON.stringify([row.document.eventSessionId, row.document.id]),
          row,
        ]),
      );
      for (const write of writes) {
        const key = JSON.stringify([partition, write.document.id]);
        const existing = rows.get(key);
        if (write.operation === 'create' && existing !== undefined)
          throw new StateConflict();
        if (write.operation === 'replace' && existing?.etag !== write.etag)
          throw new StateConflict();
        rows.set(key, {
          document: structuredClone(write.document),
          etag: `${String(current.revision + 1)}-${write.document.id}`,
        });
      }
      const next: DiskState = {
        revision: current.revision + 1,
        rows: [...rows.values()],
      };
      const temporary = `${this.path}.next`;
      await writeFile(temporary, JSON.stringify(next));
      await rename(temporary, this.path);
      this.batches.push(structuredClone(writes));
      if (writes.some(({ document }) => document.kind === this.failAfterKind)) {
        this.failAfterKind = undefined;
        throw this.#failure();
      }
    });
  }

  #failure() {
    return new ApiProblem({
      code: 'injected-storage-failure',
      messageKey: 'test.storage.failure',
      status: 503,
      title: 'Injected storage failure',
      retryAfterSeconds: 1,
    });
  }

  check(): Promise<'up' | 'down'> {
    return Promise.resolve('up');
  }

  close(): void {}
}
