targetScope = 'resourceGroup'

metadata description = 'Managed identities, Key Vault, and least-privilege secret access.'

@description('Azure region for identity and Key Vault resources.')
param location string

@description('Resource names generated by the shared naming module.')
param names object

@description('Common tags generated by the shared tagging module.')
param tags object

@description('Number of days soft-deleted vaults and objects are retained.')
@minValue(7)
@maxValue(90)
param softDeleteRetentionInDays int = 7

@description('Protect the vault from purge during the soft-delete retention period.')
param purgeProtectionEnabled bool = true

var keyVaultSecretsUserRoleId = '4633458b-17de-408a-b874-0445c86b69e6'

resource apiIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: names.apiIdentity
  location: location
  tags: tags
}

resource dashboardIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: names.dashboardIdentity
  location: location
  tags: tags
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: names.keyVault
  location: location
  tags: tags
  properties: {
    enablePurgeProtection: purgeProtectionEnabled
    enableRbacAuthorization: true
    enabledForDeployment: false
    enabledForDiskEncryption: false
    enabledForTemplateDeployment: false
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
    publicNetworkAccess: 'Enabled'
    sku: {
      family: 'A'
      name: 'standard'
    }
    softDeleteRetentionInDays: softDeleteRetentionInDays
    tenantId: tenant().tenantId
  }
}

resource apiKeyVaultSecretsUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, apiIdentity.id, keyVaultSecretsUserRoleId)
  scope: keyVault
  properties: {
    principalId: apiIdentity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', keyVaultSecretsUserRoleId)
  }
}

output apiIdentityClientId string = apiIdentity.properties.clientId
output apiIdentityId string = apiIdentity.id
output apiIdentityPrincipalId string = apiIdentity.properties.principalId
output dashboardIdentityClientId string = dashboardIdentity.properties.clientId
output dashboardIdentityId string = dashboardIdentity.id
output dashboardIdentityPrincipalId string = dashboardIdentity.properties.principalId
output keyVaultId string = keyVault.id
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
