targetScope = 'resourceGroup'

metadata description = 'Passwordless Azure SignalR Service and diagnostics.'

@description('Azure region for SignalR Service.')
param location string

@description('Resource names generated by the shared naming module.')
param names object

@description('Common tags generated by the shared tagging module.')
param tags object

@description('Principal ID of the Mission Control API managed identity.')
param apiPrincipalId string

@description('Log Analytics workspace resource ID for SignalR diagnostics.')
param logAnalyticsWorkspaceId string

var signalRAppServerRoleId = '420fcaa2-552c-430f-98ca-3264be4806c7'

resource signalR 'Microsoft.SignalRService/signalR@2024-03-01' = {
  name: names.signalRService
  location: location
  tags: tags
  kind: 'SignalR'
  sku: {
    capacity: 1
    name: 'Standard_S1'
    tier: 'Standard'
  }
  properties: {
    cors: {}
    disableAadAuth: false
    disableLocalAuth: true
    features: [
      {
        flag: 'ServiceMode'
        value: 'Default'
      }
      {
        flag: 'EnableConnectivityLogs'
        value: 'True'
      }
      {
        flag: 'EnableMessagingLogs'
        value: 'False'
      }
      {
        flag: 'EnableLiveTrace'
        value: 'False'
      }
    ]
    publicNetworkAccess: 'Enabled'
    tls: {
      clientCertEnabled: false
    }
  }
}

resource apiSignalRAppServer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(signalR.id, apiPrincipalId, signalRAppServerRoleId)
  scope: signalR
  properties: {
    principalId: apiPrincipalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', signalRAppServerRoleId)
  }
}

resource signalRDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'signalr-diagnostics'
  scope: signalR
  properties: {
    logs: [
      {
        category: 'ConnectivityLogs'
        enabled: true
      }
      {
        category: 'HttpRequestLogs'
        enabled: true
      }
    ]
    workspaceId: logAnalyticsWorkspaceId
  }
}

output hostName string = signalR.properties.hostName
output id string = signalR.id
output name string = signalR.name
output serviceUri string = 'https://${signalR.properties.hostName}'
