targetScope = 'resourceGroup'

metadata description = 'Passwordless Azure SignalR Service and diagnostics.'

@description('Azure region for SignalR Service.')
param location string

@description('Resource names generated by the shared naming module.')
param names object

@description('Common tags generated by the shared tagging module.')
param tags object

@description('Principal ID of the Mission Control API managed identity.')
param apiPrincipalId string

@description('Exact dashboard origins, resolved before promotion. Empty for non-operational bootstrap.')
@maxLength(1)
param allowedOrigins string[]

@description('Log Analytics workspace resource ID for SignalR diagnostics.')
param logAnalyticsWorkspaceId string

var signalRRestApiOwnerRoleId = 'fd53cd77-2268-407a-8f46-7e7863d0f521'

resource signalR 'Microsoft.SignalRService/signalR@2024-03-01' = {
  name: names.signalRService
  location: location
  tags: tags
  kind: 'SignalR'
  sku: {
    capacity: 1
    name: 'Standard_S1'
    tier: 'Standard'
  }
  properties: {
    cors: { allowedOrigins: allowedOrigins }
    disableAadAuth: false
    disableLocalAuth: true
    features: [
      {
        flag: 'ServiceMode'
        value: 'Serverless'
      }
      {
        flag: 'EnableConnectivityLogs'
        value: 'True'
      }
      {
        flag: 'EnableMessagingLogs'
        value: 'False'
      }
      {
        flag: 'EnableLiveTrace'
        value: 'False'
      }
    ]
    publicNetworkAccess: 'Enabled'
    tls: {
      clientCertEnabled: false
    }
  }
}

resource apiSignalRRestApiOwner 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(signalR.id, apiPrincipalId, signalRRestApiOwnerRoleId)
  scope: signalR
  properties: {
    principalId: apiPrincipalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', signalRRestApiOwnerRoleId)
  }
}

resource signalRDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'signalr-diagnostics'
  scope: signalR
  properties: {
    logs: [
      {
        category: 'ConnectivityLogs'
        enabled: true
      }
      {
        category: 'HttpRequestLogs'
        enabled: true
      }
    ]
    workspaceId: logAnalyticsWorkspaceId
  }
}

output hostName string = signalR.properties.hostName
output id string = signalR.id
output name string = signalR.name
output serviceUri string = 'https://${signalR.properties.hostName}'
